title: Maggie's Corner of the Internet ✨
description: >
  IT Business Architect turned strategy geek, currently on a joyful pivot toward
  transformation, growth, and big bold ideas. Built with curiosity, a few too many
  browser tabs, and a whole lot of heart. 💛

theme: jekyll-theme-cayman
